name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t frontend -f dockerfile.dev .
      - run: docker run -e CI=true frontend npm test
      - name: create ZIP folder
        run: zip -r front.zip . -x "*.git*"
      - name: deploy to aws beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          region: us-east-1
          application_name: frontend
          environment_name: Frontend-env
          deployment_package: front.zip
          version_label: 8
          aws_access_key: ${{ secrets.AWS_ACCESS }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET }}
